# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Graecians Heroes
tagline:          'Discover the best of Greece'
description:      'Μια affiliate σελίδα με μέρη και ξενοδοχεία σε όλη την Ελλάδα.'

navigation:
  - title: "Αρχική"
    url: "/"
  - title: "Σαντορίνη"
    url: "/santorini/"
  - title: "Μύκονος"
    url: "/mykonos/"
  - title: "Επικοινωνία"
    url: "/contact/"
